services:
  postgres:
    restart: always
    image: "postgres:16"
    ports:
      - "5432"
    environment:
      POSTGRES_DB: thingsboard
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

  thingsboard-ce:
    restart: always
    image: "thingsboard/tb-node:4.2.1.1"
    ports:
      - "8080:8080"
      - "7070:7070"
      - "8883:8883"
      - "0.0.0.0:1883:1883"
      - "5684:5684/udp"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/thingsboard
      TB_SERVICE_ID: tb-ce-node

      MQTT_BIND_ADDRESS: "0.0.0.0"

      # --- CONFIGURACIÓN MQTT TLS ---
      MQTT_SSL_ENABLED: "true"
      MQTT_SSL_BIND_ADDRESS: "0.0.0.0"
      MQTT_SSL_BIND_PORT: "8883"
      MQTT_SSL_CREDENTIALS_TYPE: "PEM"
      MQTT_SSL_PEM_CERT: "/etc/thingsboard/conf/server_mqtt.pem"
      MQTT_SSL_PEM_KEY: "/etc/thingsboard/conf/server_mqtt_key.pem"

      # --- CONFIGURACIÓN COAP DTLS ---
      COAP_DTLS_ENABLED: "true"
      COAP_DTLS_BIND_ADDRESS: "0.0.0.0"
      COAP_DTLS_BIND_PORT: "5684"
      COAP_DTLS_CREDENTIALS_TYPE: "PEM"
      COAP_DTLS_PEM_CERT: "/etc/thingsboard/conf/server_coap.pem"
      COAP_DTLS_PEM_KEY: "/etc/thingsboard/conf/server_coap_key.pem"

    volumes:
      - ./certs/server_mqtt.pem:/etc/thingsboard/conf/server_mqtt.pem:ro
      - ./certs/server_mqtt_key.pem:/etc/thingsboard/conf/server_mqtt_key.pem:ro
      - ./certs/server_coap.pem:/etc/thingsboard/conf/server_coap.pem:ro
      - ./certs/server_coap_key.pem:/etc/thingsboard/conf/server_coap_key.pem:ro
    depends_on:
      - postgres

volumes:
  postgres-data:
    name: tb-postgres-data
