services:
  postgres:
    restart: always
    image: "postgres:16"
    ports:
      - "5432"
    environment:
      POSTGRES_DB: thingsboard
    volumes:
      - postgres-data:/var/lib/postgresql/data

  thingsboard-ce:
    restart: always
    image: "thingsboard/tb-node:4.2.1.1"
    ports:
      - "8080:8080"
      - "7070:7070"
      - "8883:8883"
      - "5683-5688:5683-5688/udp"
    environment:
      TB_SERVICE_ID: tb-ce-node
      # --- CONFIGURACIÓN DB (Crucial) ---
      DATABASE_TS_TYPE: sql
      DATABASE_ENTITIES_TYPE: sql
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/thingsboard
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      # --- CONFIGURACIÓN MQTT TLS ---
      MQTT_SSL_ENABLED: "true"
      MQTT_SSL_BIND_ADDRESS: "0.0.0.0"
      MQTT_SSL_BIND_PORT: "8883"
      MQTT_SSL_CREDENTIALS_TYPE: "PEM"
      MQTT_SSL_PEM_CERT: "/etc/thingsboard/conf/server.pem"
      MQTT_SSL_PEM_KEY: "/etc/thingsboard/conf/server_key.pem"

      # --- CONFIGURACIÓN COAP DTLS ---
      COAP_DTLS_ENABLED: "true"
      COAP_DTLS_BIND_ADDRESS: "0.0.0.0"
      COAP_DTLS_BIND_PORT: "5684"
      COAP_DTLS_CREDENTIALS_TYPE: "PEM"
      COAP_DTLS_PEM_CERT: "/etc/thingsboard/conf/server.pem"
      COAP_DTLS_PEM_KEY: "/etc/thingsboard/conf/server_key.pem"

    volumes:
      - ./certs/server.pem:/etc/thingsboard/conf/server.pem:ro
      - ./certs/server_key.pem:/etc/thingsboard/conf/server_key.pem:ro
      - tb-data:/data # VOLUMEN NUEVO para datos de la aplicación
      - tb-logs:/var/log/thingsboard # OPCIONAL: Para ver logs fácilmente
    depends_on:
      - postgres

volumes:
  postgres-data:
    name: tb-postgres-data
  tb-data:
    name: tb-app-data
  tb-logs:
    name: tb-app-logs
