/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_TELEMETRY_TELEMETRY_PB_H_INCLUDED
#define PB_TELEMETRY_TELEMETRY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _telemetry_SensorDataReading {
    double mcu_temp;
    int32_t rssi;
    uint32_t free_heap;
} telemetry_SensorDataReading;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define telemetry_SensorDataReading_init_default {0, 0, 0}
#define telemetry_SensorDataReading_init_zero    {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define telemetry_SensorDataReading_mcu_temp_tag 1
#define telemetry_SensorDataReading_rssi_tag     2
#define telemetry_SensorDataReading_free_heap_tag 3

/* Struct field encoding specification for nanopb */
#define telemetry_SensorDataReading_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   mcu_temp,          1) \
X(a, STATIC,   SINGULAR, INT32,    rssi,              2) \
X(a, STATIC,   SINGULAR, UINT32,   free_heap,         3)
#define telemetry_SensorDataReading_CALLBACK NULL
#define telemetry_SensorDataReading_DEFAULT NULL

extern const pb_msgdesc_t telemetry_SensorDataReading_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define telemetry_SensorDataReading_fields &telemetry_SensorDataReading_msg

/* Maximum encoded size of messages (where known) */
#define TELEMETRY_TELEMETRY_PB_H_MAX_SIZE        telemetry_SensorDataReading_size
#define telemetry_SensorDataReading_size         26

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
